# -*- coding: utf-8 -*-
"""Read the Financial Statement

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uszcvyp1u3AISpBES5JzCp0uL3C8Lgz3

# Reading the Financial Statement using Python
"""

import yfinance as yf

#import libraries

"""# Balance Sheet"""

# Create the functions forget access for balance sheet
def get_balance_sheet_data(symbol):
    # for company symbol
    company = yf.Ticker(symbol)
    # get access of balancesheet
    balance_sheet = company.balance_sheet
    return balance_sheet

symbol = "TCS"
# balance sheet
balance_sheet_data = get_balance_sheet_data(symbol)
balance_sheet_data

"""# Cash Flow Statement"""

# Create the function for cash Flow statement
def get_cash_flow_data(symbol):
    company = yf.Ticker(symbol)
    cash = company.cash_flow
    return cash

symbol = "TCS" # Change the comapny symbol as per your requirement
get_cash_flow_data = get_cash_flow_data(symbol)
get_cash_flow_data

"""# Income Statement"""

# Create the function for Income Statement
def get_income_statement_data(symbol):
    company = yf.Ticker(symbol)
    inc = company.financials
    return inc

symbol = "TCS" # Change the comapny symbol as per your requirement
get_income_statement_data = get_income_statement_data(symbol)
get_income_statement_data